# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/ruby/tags/
image: "ruby:2.6"

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby
    - build

before_script:
  - apt-get update -y
  - apt-get install -y openssh-client rsync locales
  - echo "pl_PL UTF-8" > /etc/locale.gen
  - locale-gen pl_PL.UTF-8
  - export LANG=pl_PL.UTF-8
  - export LANGUAGE=pl_PL:en
  - export LC_ALL=pl_PL.UTF-8
  - ruby -v
  - gem install bundler  --no-document
  - bundle install -j $(nproc) --path vendor


middleman:
  script:
  - bundle exec middleman build --clean --parallel --build-dir=public
  artifacts:
    paths:
      - public/
    expire_in: 1 week

# This deploy job uses a simple deploy flow to Heroku, other providers, e.g. AWS Elastic Beanstalk
# are supported too: https://github.com/travis-ci/dpl
deploy:
  type: deploy
  environment: production
  script:
  - bundle exec middleman build --clean --parallel --build-dir=public
